name: loan_simulations
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.6.1
  animate_do: ^3.0.2
  flutter_svg: ^2.0.0+1
  lottie: ^2.2.0
  currency_text_input_formatter: ^2.1.8
  flutter_dotenv: ^5.0.2
  uno: ^1.0.1+5
  multi_select_flutter: ^4.1.3

dependency_overrides:
  get:
    git:
      url: https://github.com/jonataslaw/getx.git
      ref: 7479982b2eb137352a2ea4d3491686eae718d28b

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/svgs/
    - assets/images/webps/
    - assets/lotties/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
